"""Per-category report templates in English and Nepali.

Slots: {place}, {duration}. Each category carries several distinct framings so
the classifier cannot win by memorising one keyword -- "water" appears in
water_supply, drainage and waterlogging, and has to be disambiguated by
context.
"""

TEMPLATES: dict[str, dict[str, list[str]]] = {
    "pothole": {
        "en": [
            "There is a big pothole on the road {place}. It has been there {duration}.",
            "The road surface {place} is completely broken and full of holes.",
            "Deep pothole {place}, motorcycles are falling into it every day.",
            "Road damage {place} has become dangerous {duration}.",
            "The blacktop {place} has come off and the road is full of pits.",
            "A large hole has opened up in the middle of the road {place}.",
            "Vehicles are getting damaged because of the broken road {place}.",
            "The road {place} needs repair, there are craters everywhere {duration}.",
        ],
        "ne": [
            "{place} सडकमा ठूलो खाल्डो छ। {duration} यस्तै छ।",
            "{place} सडक पूरै भत्किएको छ र खाल्डाखुल्डी छन्।",
            "{place} गहिरो खाल्डो छ, मोटरसाइकल दैनिक लड्छन्।",
            "{place} सडक क्षति भएर {duration} जोखिमपूर्ण भएको छ।",
            "{place} कालोपत्रे उप्किएर बाटो खाल्डैखाल्डो भयो।",
            "सडकको बीचमा {place} ठूलो प्वाल परेको छ।",
            "{place} फुटेको सडकका कारण सवारी बिग्रिरहेका छन्।",
            "{place} सडक मर्मत गर्नुपर्‍यो, {duration} खाल्डो छ।",
        ],
    },
    "garbage": {
        "en": [
            "Garbage has been piling up {place} {duration}.",
            "Nobody has collected the waste {place}, it smells terrible.",
            "A heap of trash {place} is attracting dogs and flies.",
            "Waste is dumped openly {place} and no one clears it.",
            "The garbage container {place} is overflowing {duration}.",
            "People are throwing household waste {place} every morning.",
            "Rubbish scattered all over the street {place}.",
            "The waste collection vehicle has not come {place} {duration}.",
        ],
        "ne": [
            "{place} {duration} फोहोर थुप्रिएको छ।",
            "{place} फोहोर उठाएको छैन, दुर्गन्ध आइरहेको छ।",
            "{place} फोहोरको थुप्रोले कुकुर र झिंगा आउँछन्।",
            "{place} खुला रूपमा फोहोर फालिन्छ, कसैले सफा गर्दैन।",
            "{place} फोहोर कन्टेनर {duration} भरिएर पोखिएको छ।",
            "बिहान बिहान मानिसहरू {place} घरको फोहोर फाल्छन्।",
            "{place} सडकभरि फोहोर छरिएको छ।",
            "{place} {duration} फोहोर उठाउने गाडी आएको छैन।",
        ],
    },
    "street_light": {
        "en": [
            "The street light {place} has not been working {duration}.",
            "It is pitch dark {place} at night because the lamp is fused.",
            "Street lamp {place} is broken and the pole is leaning.",
            "No lighting {place}, women feel unsafe walking at night.",
            "The bulb of the street light {place} went out {duration}.",
            "Half the street lights on this stretch {place} are dead.",
            "The light {place} flickers all night and then goes off.",
            "Please repair the road light {place}, it is very dark.",
        ],
        "ne": [
            "{place} सडक बत्ती {duration} बलेको छैन।",
            "बत्ती नबलेकाले राति {place} अँध्यारो हुन्छ।",
            "{place} सडक बत्ती बिग्रिएको छ र पोल ढल्किएको छ।",
            "{place} उज्यालो छैन, राति महिलाहरू हिँड्न डराउँछन्।",
            "{place} सडक बत्तीको बल्ब {duration} फुटेको छ।",
            "यो खण्डमा {place} आधा सडक बत्ती बलेका छैनन्।",
            "{place} बत्ती रातभरि टिमटिम गरेर निभ्छ।",
            "कृपया {place} सडक बत्ती मर्मत गरिदिनुहोस्, धेरै अँध्यारो छ।",
        ],
    },
    "water_supply": {
        "en": [
            "There has been no drinking water supply {place} {duration}.",
            "The tap {place} has run dry, we are buying tanker water.",
            "Water comes only once a week {place}.",
            "The supply pipe {place} is leaking and pressure is very low.",
            "No water in the household taps {place} {duration}.",
            "Drinking water {place} is coming dirty and smells of mud.",
            "The community tap {place} has not been repaired {duration}.",
            "Water supply schedule {place} has not been followed at all.",
        ],
        "ne": [
            "{place} {duration} खानेपानी आएको छैन।",
            "{place} धारा सुकेको छ, ट्यांकरको पानी किन्नु परेको छ।",
            "{place} हप्तामा एकपटक मात्र पानी आउँछ।",
            "{place} पाइप चुहिएर पानीको प्रेसर एकदमै कम छ।",
            "{place} घरको धारामा {duration} पानी छैन।",
            "{place} खानेपानी फोहोर र हिलोको गन्ध आउने आइरहेको छ।",
            "{place} सामुदायिक धारा {duration} मर्मत भएको छैन।",
            "{place} खानेपानी वितरण तालिका पालना भएको छैन।",
        ],
    },
    "drainage": {
        "en": [
            "The drain {place} is completely blocked {duration}.",
            "Sewage is overflowing onto the road {place}.",
            "The drainage cover {place} is missing and it is dangerous.",
            "Dirty sewer water is coming up {place} and the smell is unbearable.",
            "The open drain {place} has been clogged with plastic {duration}.",
            "Sewer line {place} burst and waste water is spreading.",
            "Blocked sewage {place} is flowing into the houses nearby.",
            "The drain {place} has not been cleaned {duration}.",
        ],
        "ne": [
            "{place} ढल {duration} पूरै जाम भएको छ।",
            "{place} ढलको पानी सडकमा पोखिएको छ।",
            "{place} ढलको ढक्कन हराएको छ, जोखिमपूर्ण छ।",
            "{place} फोहोर ढलको पानी उम्रिएर असह्य गन्ध आउँछ।",
            "{place} खुला ढल {duration} प्लास्टिकले बन्द भएको छ।",
            "{place} ढल लाइन फुटेर फोहोर पानी फैलिएको छ।",
            "{place} जाम भएको ढल छिमेकी घरमा पस्दै छ।",
            "{place} ढल {duration} सफा गरिएको छैन।",
        ],
    },
    "waterlogging": {
        "en": [
            "The whole road {place} is under water after the rain.",
            "Water logging {place} has made the street impassable {duration}.",
            "Rain water has flooded the area {place}, knee deep in places.",
            "Every time it rains the road {place} turns into a pond.",
            "Flooding {place} has entered the ground floor of houses.",
            "The street {place} is waterlogged and vehicles cannot pass.",
            "Standing water {place} {duration} is breeding mosquitoes.",
            "The low area {place} floods badly whenever it rains hard.",
        ],
        "ne": [
            "पानी परेपछि {place} सडक पूरै डुबेको छ।",
            "{place} जलजमावले {duration} बाटो हिँड्नै नसकिने भएको छ।",
            "{place} वर्षाको पानीले क्षेत्र डुबेको छ, घुँडासम्म पानी छ।",
            "पानी परेपिच्छे {place} सडक पोखरी बन्छ।",
            "{place} बाढीको पानी घरको भुइँतलामा पसेको छ।",
            "{place} सडकमा पानी जमेर सवारी गुड्न सकेका छैनन्।",
            "{place} {duration} जमेको पानीमा लामखुट्टे बढेको छ।",
            "{place} होचो ठाउँमा ठूलो पानी परेपछि डुबान हुन्छ।",
        ],
    },
    "electricity": {
        "en": [
            "The electricity pole {place} is leaning dangerously {duration}.",
            "Live wires are hanging low {place}, children pass under them.",
            "There has been no power supply {place} {duration}.",
            "Transformer {place} is sparking and making loud noises.",
            "The electric wire {place} snapped and is lying on the road.",
            "Frequent power cuts {place} {duration}, sometimes all night.",
            "The distribution box {place} is open and wires are exposed.",
            "Power line {place} is touching the tree branches, very risky.",
        ],
        "ne": [
            "{place} बिजुलीको पोल {duration} जोखिमपूर्ण गरी ढल्किएको छ।",
            "{place} करेन्ट भएको तार होचो झुन्डिएको छ, बच्चाहरू तलबाट हिँड्छन्।",
            "{place} {duration} बिजुली आएको छैन।",
            "{place} ट्रान्सफर्मरबाट आगोको झिल्का निस्किएर ठूलो आवाज आउँछ।",
            "{place} बिजुलीको तार चुँडिएर सडकमा लडेको छ।",
            "{place} {duration} पटक पटक बिजुली जान्छ, कहिले रातभरि।",
            "{place} वितरण बाकस खुला छ र तारहरू बाहिर देखिन्छन्।",
            "{place} बिजुलीको लाइन रूखको हाँगामा छोइएको छ, जोखिम छ।",
        ],
    },
    "stray_animals": {
        "en": [
            "A pack of stray dogs {place} is chasing people {duration}.",
            "Cows are sitting in the middle of the road {place}, blocking traffic.",
            "Stray dogs {place} bit a child yesterday.",
            "Abandoned cattle {place} are eating from the garbage pile.",
            "The dogs {place} bark all night and nobody can sleep.",
            "Street animals {place} have become a danger for school children.",
            "Monkeys {place} are entering houses and taking food.",
            "Stray animals roaming {place} {duration}, please manage them.",
        ],
        "ne": [
            "{place} छाडा कुकुरको हुल {duration} मानिसलाई खेद्छ।",
            "{place} सडकको बीचमा गाई बसेर ट्राफिक रोकिएको छ।",
            "{place} छाडा कुकुरले हिजो बच्चालाई टोक्यो।",
            "{place} छाडा गाईवस्तुले फोहोरको थुप्रोबाट खाइरहेका छन्।",
            "{place} कुकुर रातभरि भुक्छन्, कसैले सुत्न पाउँदैन।",
            "{place} सडकका पशुले स्कूले बालबालिकालाई जोखिम भएको छ।",
            "{place} बाँदरहरू घरमा पसेर खाना लैजान्छन्।",
            "{place} {duration} छाडा पशु घुमिरहेका छन्, व्यवस्थापन गरिदिनुहोस्।",
        ],
    },
    "public_sanitation": {
        "en": [
            "The public toilet {place} is filthy and has no water {duration}.",
            "No one has cleaned the public area {place} {duration}.",
            "The public washroom {place} is locked and unusable.",
            "People are urinating openly {place} because there is no toilet.",
            "The sanitation of the market area {place} is very poor.",
            "The public toilet {place} has broken doors and no lighting.",
            "Cleaning staff have not come to {place} {duration}.",
            "The community washroom {place} needs urgent maintenance.",
        ],
        "ne": [
            "{place} सार्वजनिक शौचालय {duration} फोहोर छ र पानी छैन।",
            "{place} सार्वजनिक क्षेत्र {duration} कसैले सफा गरेको छैन।",
            "{place} सार्वजनिक शौचालय बन्द छ, प्रयोग गर्न मिल्दैन।",
            "शौचालय नभएकाले मानिसहरू {place} खुला ठाउँमा पिसाब गर्छन्।",
            "{place} बजार क्षेत्रको सरसफाइ एकदमै नराम्रो छ।",
            "{place} सार्वजनिक शौचालयको ढोका फुटेको र बत्ती छैन।",
            "{place} {duration} सफाइ कर्मचारी आएका छैनन्।",
            "{place} सामुदायिक शौचालयको तत्काल मर्मत आवश्यक छ।",
        ],
    },
    "illegal_construction": {
        "en": [
            "Someone is building a wall on public land {place}.",
            "A house {place} has been extended over the footpath {duration}.",
            "Construction {place} is going on without any permit.",
            "The builder {place} has occupied half the road with materials.",
            "Illegal structure {place} is blocking the public path.",
            "They are constructing {place} beyond the approved boundary.",
            "Shops {place} have encroached on the pavement {duration}.",
            "Unauthorised construction {place}, please inspect it.",
        ],
        "ne": [
            "{place} सार्वजनिक जग्गामा कसैले पर्खाल लगाउँदै छ।",
            "{place} घरले {duration} फुटपाथ मिचेर बढाइएको छ।",
            "{place} कुनै अनुमति नलिई निर्माण भइरहेको छ।",
            "{place} निर्माण सामग्रीले आधा सडक ओगटेको छ।",
            "{place} अवैध संरचनाले सार्वजनिक बाटो छेकेको छ।",
            "{place} स्वीकृत सीमा नाघेर निर्माण गरिँदै छ।",
            "{place} पसलहरूले {duration} फुटपाथ मिचेका छन्।",
            "{place} अनधिकृत निर्माण भएको छ, निरीक्षण गरिदिनुहोस्।",
        ],
    },
    "pollution": {
        "en": [
            "Dust from the road {place} is unbearable {duration}.",
            "A factory {place} is releasing black smoke all day.",
            "Loud music from the party palace {place} goes on past midnight.",
            "Construction dust {place} is causing breathing problems.",
            "Vehicles {place} are emitting thick black smoke.",
            "The noise from generators {place} is constant {duration}.",
            "Burning of waste {place} is filling the area with smoke.",
            "Air quality {place} has become very bad {duration}.",
        ],
        "ne": [
            "{place} सडकको धुलो {duration} असह्य भएको छ।",
            "{place} कारखानाले दिनभरि कालो धुवाँ निकाल्छ।",
            "{place} पार्टी प्यालेसको ठूलो आवाज मध्यरातसम्म चल्छ।",
            "{place} निर्माणको धुलोले सास फेर्न गाह्रो भएको छ।",
            "{place} सवारी साधनले बाक्लो कालो धुवाँ फाल्छन्।",
            "{place} जेनेरेटरको आवाज {duration} लगातार छ।",
            "{place} फोहोर बालेर क्षेत्रभरि धुवाँ भएको छ।",
            "{place} हावाको गुणस्तर {duration} एकदमै खराब भएको छ।",
        ],
    },
    "other": {
        "en": [
            "There is a problem {place} that needs the ward office to look at.",
            "Something needs attention {place}, it has been ignored {duration}.",
            "We have an issue {place}, please send someone to inspect.",
            "A public facility {place} is damaged and unusable {duration}.",
            "The bench and railing {place} are broken.",
            "The public notice board {place} has fallen down.",
            "The park equipment {place} is damaged and unsafe for children.",
            "The bus stop shelter {place} is broken {duration}.",
        ],
        "ne": [
            "{place} वडा कार्यालयले हेर्नुपर्ने समस्या छ।",
            "{place} {duration} बेवास्ता गरिएको कुरा छ, ध्यान दिनुपर्‍यो।",
            "{place} समस्या छ, कृपया कसैलाई निरीक्षणका लागि पठाउनुहोस्।",
            "{place} सार्वजनिक संरचना {duration} बिग्रिएर प्रयोगविहीन छ।",
            "{place} बेन्च र रेलिङ फुटेको छ।",
            "{place} सार्वजनिक सूचना पाटी ढलेको छ।",
            "{place} पार्कका सामग्री बिग्रिएर बालबालिकालाई असुरक्षित छ।",
            "{place} बस स्टपको छाप्रो {duration} भत्किएको छ।",
        ],
    },
}

TITLES: dict[str, tuple[str, str]] = {
    "pothole": ("Pothole on the road", "सडकमा खाल्डो"),
    "garbage": ("Garbage not collected", "फोहोर उठेन"),
    "street_light": ("Street light not working", "सडक बत्ती बलेन"),
    "water_supply": ("No water supply", "खानेपानी आएन"),
    "drainage": ("Drain blocked", "ढल जाम"),
    "waterlogging": ("Road flooded", "सडक डुबान"),
    "electricity": ("Electricity hazard", "विद्युत जोखिम"),
    "stray_animals": ("Stray animals", "छाडा पशु"),
    "public_sanitation": ("Public sanitation problem", "सार्वजनिक सरसफाइ समस्या"),
    "illegal_construction": ("Illegal construction", "अवैध निर्माण"),
    "pollution": ("Pollution problem", "प्रदूषण समस्या"),
    "other": ("Other civic issue", "अन्य नागरिक समस्या"),
}
