"""initial civic platform schema

Revision ID: a5ee60c2664f
Revises: 
Create Date: 2026-09-18 18:49:28.603022

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# Every table is locked down with RLS and no policies. Supabase exposes any
# RLS-disabled table to the browser anon key through PostgREST, so this is
# what keeps the frontend from reading the tickets table directly. The
# backend uses the service-role key and is unaffected.
RLS_TABLES = [
    "municipalities",
    "wards",
    "categories",
    "profiles",
    "tickets",
    "ticket_photos",
    "ticket_corroborations",
    "duplicate_candidates",
    "ticket_status_history",
    "sos_requests",
    "alerts",
    "civic_services",
    "notifications",
]


# revision identifiers, used by Alembic.
revision: str = 'a5ee60c2664f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before tickets.embedding is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ne', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('base_severity', sa.Float(), nullable=False),
    sa.Column('match_radius_m', sa.Integer(), nullable=False),
    sa.Column('dedupe_window_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('municipalities',
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ne', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('METROPOLITAN', 'SUB_METROPOLITAN', 'MUNICIPALITY', 'RURAL_MUNICIPALITY', name='municipality_type'), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('wards',
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('name_ne', sa.String(length=120), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'number', name='uq_ward_number')
    )
    op.create_index(op.f('ix_wards_municipality_id'), 'wards', ['municipality_id'], unique=False)
    op.create_table('civic_services',
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ne', sa.String(length=200), nullable=True),
    sa.Column('service_type', sa.Enum('HOSPITAL', 'AMBULANCE', 'POLICE', 'FIRE', 'WARD_OFFICE', 'MUNICIPALITY_OFFICE', 'SHELTER', 'PHARMACY', 'OTHER', name='service_type'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('alt_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('is_24x7', sa.Boolean(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('notes_en', sa.Text(), nullable=True),
    sa.Column('notes_ne', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_civic_services_municipality_id'), 'civic_services', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_civic_services_service_type'), 'civic_services', ['service_type'], unique=False)
    op.create_index(op.f('ix_civic_services_ward_id'), 'civic_services', ['ward_id'], unique=False)
    op.create_index('ix_service_type_ward', 'civic_services', ['service_type', 'ward_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'AUTHORITY', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('account_status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'SUSPENDED', name='account_status'), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('preferred_language', sa.Enum('EN', 'NE', name='language'), nullable=False),
    sa.Column('large_text', sa.Boolean(), nullable=False),
    sa.Column('high_contrast', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_profiles_account_status'), 'profiles', ['account_status'], unique=False)
    op.create_index(op.f('ix_profiles_municipality_id'), 'profiles', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_profiles_role'), 'profiles', ['role'], unique=False)
    op.create_index(op.f('ix_profiles_ward_id'), 'profiles', ['ward_id'], unique=False)
    op.create_table('alerts',
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ne', sa.String(length=200), nullable=True),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_ne', sa.Text(), nullable=True),
    sa.Column('instructions_en', sa.Text(), nullable=True),
    sa.Column('instructions_ne', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('target_type', sa.Enum('WARD', 'RADIUS', name='alert_target_type'), nullable=False),
    sa.Column('ward_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_by_id'), 'alerts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_alerts_expires_at'), 'alerts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_alerts_municipality_id'), 'alerts', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('sos_requests',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('emergency_type', sa.Enum('MEDICAL', 'FIRE', 'POLICE', 'DISASTER', 'OTHER', name='emergency_type'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_text', sa.String(length=300), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('municipality_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'DISPATCHED', 'CLOSED', name='sos_status'), nullable=False),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_requests_citizen_id'), 'sos_requests', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_sos_requests_municipality_id'), 'sos_requests', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_sos_requests_status'), 'sos_requests', ['status'], unique=False)
    op.create_index(op.f('ix_sos_requests_ward_id'), 'sos_requests', ['ward_id'], unique=False)
    op.create_index('ix_sos_ward_status', 'sos_requests', ['ward_id', 'status'], unique=False)
    op.create_table('tickets',
    sa.Column('public_code', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_lang', sa.Enum('EN', 'NE', name='language'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_text', sa.String(length=300), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'VERIFIED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'MERGED', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('dispute_count', sa.Integer(), nullable=False),
    sa.Column('community_verified', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('predicted_category_key', sa.String(length=48), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> parent_id', name='ck_ticket_not_own_parent'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_ticket_lat'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_ticket_lon'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code')
    )
    op.create_index('ix_ticket_bbox', 'tickets', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_ticket_ward_status', 'tickets', ['ward_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_to_id'), 'tickets', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tickets_category_id'), 'tickets', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_municipality_id'), 'tickets', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_tickets_parent_id'), 'tickets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_reporter_id'), 'tickets', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ward_id'), 'tickets', ['ward_id'], unique=False)
    op.create_table('duplicate_candidates',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('candidate_ticket_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category_score', sa.Float(), nullable=False),
    sa.Column('text_score', sa.Float(), nullable=False),
    sa.Column('image_score', sa.Float(), nullable=False),
    sa.Column('geo_score', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MERGED', 'REJECTED', name='candidate_status'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ticket_id <> candidate_ticket_id', name='ck_candidate_not_self'),
    sa.ForeignKeyConstraint(['candidate_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'candidate_ticket_id', name='uq_candidate_pair')
    )
    op.create_index(op.f('ix_duplicate_candidates_candidate_ticket_id'), 'duplicate_candidates', ['candidate_ticket_id'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_score'), 'duplicate_candidates', ['score'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_status'), 'duplicate_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_duplicate_candidates_ticket_id'), 'duplicate_candidates', ['ticket_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TICKET_STATUS_CHANGED', 'TICKET_MERGED', 'TICKET_RESOLVED', 'TICKET_CORROBORATED', 'ALERT_PUBLISHED', 'ACCOUNT_APPROVED', name='notification_type'), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ne', sa.String(length=200), nullable=True),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('body_ne', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('sos_request_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sos_request_id'], ['sos_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('ticket_corroborations',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'citizen_id', name='uq_corroboration_once')
    )
    op.create_index(op.f('ix_ticket_corroborations_citizen_id'), 'ticket_corroborations', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_ticket_corroborations_ticket_id'), 'ticket_corroborations', ['ticket_id'], unique=False)
    op.create_table('ticket_photos',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_photos_phash'), 'ticket_photos', ['phash'], unique=False)
    op.create_index(op.f('ix_ticket_photos_ticket_id'), 'ticket_photos', ['ticket_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('REPORTED', 'VERIFIED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'MERGED', name='ticket_status'), nullable=True),
    sa.Column('to_status', sa.Enum('REPORTED', 'VERIFIED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'MERGED', name='ticket_status'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    op.drop_index(op.f('ix_basic_crud_id'), table_name='basic_crud')
    op.drop_table('basic_crud')
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_crud',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('basic_crud_pkey'))
    )
    op.create_index(op.f('ix_basic_crud_id'), 'basic_crud', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_ticket_photos_ticket_id'), table_name='ticket_photos')
    op.drop_index(op.f('ix_ticket_photos_phash'), table_name='ticket_photos')
    op.drop_table('ticket_photos')
    op.drop_index(op.f('ix_ticket_corroborations_ticket_id'), table_name='ticket_corroborations')
    op.drop_index(op.f('ix_ticket_corroborations_citizen_id'), table_name='ticket_corroborations')
    op.drop_table('ticket_corroborations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notification_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_duplicate_candidates_ticket_id'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_status'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_score'), table_name='duplicate_candidates')
    op.drop_index(op.f('ix_duplicate_candidates_candidate_ticket_id'), table_name='duplicate_candidates')
    op.drop_table('duplicate_candidates')
    op.drop_index(op.f('ix_tickets_ward_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_reporter_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_parent_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_municipality_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_id'), table_name='tickets')
    op.drop_index('ix_ticket_ward_status', table_name='tickets')
    op.drop_index('ix_ticket_bbox', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_sos_ward_status', table_name='sos_requests')
    op.drop_index(op.f('ix_sos_requests_ward_id'), table_name='sos_requests')
    op.drop_index(op.f('ix_sos_requests_status'), table_name='sos_requests')
    op.drop_index(op.f('ix_sos_requests_municipality_id'), table_name='sos_requests')
    op.drop_index(op.f('ix_sos_requests_citizen_id'), table_name='sos_requests')
    op.drop_table('sos_requests')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_municipality_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_expires_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_by_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_profiles_ward_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_role'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_municipality_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_account_status'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_service_type_ward', table_name='civic_services')
    op.drop_index(op.f('ix_civic_services_ward_id'), table_name='civic_services')
    op.drop_index(op.f('ix_civic_services_service_type'), table_name='civic_services')
    op.drop_index(op.f('ix_civic_services_municipality_id'), table_name='civic_services')
    op.drop_table('civic_services')
    op.drop_index(op.f('ix_wards_municipality_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_table('municipalities')
    op.drop_table('categories')
    # ### end Alembic commands ###
