"""Civic service directory seed.

Organisation names and the national emergency short codes (100 police, 101
fire, 102 ambulance, 103 traffic) are real and publicly published. Street
addresses and coordinates are approximate -- good enough to render a map and
sort by distance, not a substitute for an official dataset.
"""

# Nationwide hotlines. These have no coordinates: they are not a place you go.
NATIONAL_HOTLINES: list[dict] = [
    {
        "name_en": "Nepal Police Emergency",
        "name_ne": "नेपाल प्रहरी आपतकालीन",
        "service_type": "police",
        "phone": "100",
        "is_24x7": True,
        "is_emergency": True,
        "notes_en": "Nationwide police emergency number.",
        "notes_ne": "देशभरको प्रहरी आपतकालीन नम्बर।",
    },
    {
        "name_en": "Fire Brigade",
        "name_ne": "दमकल",
        "service_type": "fire",
        "phone": "101",
        "is_24x7": True,
        "is_emergency": True,
        "notes_en": "Nationwide fire emergency number.",
        "notes_ne": "देशभरको आगलागी आपतकालीन नम्बर।",
    },
    {
        "name_en": "Ambulance Service",
        "name_ne": "एम्बुलेन्स सेवा",
        "service_type": "ambulance",
        "phone": "102",
        "is_24x7": True,
        "is_emergency": True,
        "notes_en": "Nationwide ambulance number.",
        "notes_ne": "देशभरको एम्बुलेन्स नम्बर।",
    },
    {
        "name_en": "Traffic Police",
        "name_ne": "ट्राफिक प्रहरी",
        "service_type": "police",
        "phone": "103",
        "is_24x7": True,
        "is_emergency": True,
        "notes_en": "Road accidents and traffic obstruction.",
        "notes_ne": "सडक दुर्घटना तथा ट्राफिक अवरोध।",
    },
    {
        "name_en": "Tourist Police",
        "name_ne": "पर्यटक प्रहरी",
        "service_type": "police",
        "phone": "1144",
        "is_24x7": True,
        "is_emergency": False,
    },
]

# Located services. municipality_code attaches them to a seeded municipality.
LOCATED_SERVICES: list[dict] = [
    # --- Hospitals: Kathmandu ---
    {
        "name_en": "Bir Hospital",
        "name_ne": "वीर अस्पताल",
        "service_type": "hospital",
        "phone": "01-4221119",
        "address": "Mahaboudha, Kathmandu",
        "latitude": 27.7044,
        "longitude": 85.3138,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Tribhuvan University Teaching Hospital",
        "name_ne": "त्रिभुवन विश्वविद्यालय शिक्षण अस्पताल",
        "service_type": "hospital",
        "phone": "01-4412707",
        "address": "Maharajgunj, Kathmandu",
        "latitude": 27.7357,
        "longitude": 85.3308,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Civil Service Hospital",
        "name_ne": "सिविल सेवा अस्पताल",
        "service_type": "hospital",
        "phone": "01-4107000",
        "address": "New Baneshwor, Kathmandu",
        "latitude": 27.6915,
        "longitude": 85.3357,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Kathmandu Medical College Teaching Hospital",
        "name_ne": "काठमाडौं मेडिकल कलेज",
        "service_type": "hospital",
        "phone": "01-4476152",
        "address": "Sinamangal, Kathmandu",
        "latitude": 27.6988,
        "longitude": 85.3547,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Norvic International Hospital",
        "name_ne": "नर्भिक इन्टरनेशनल अस्पताल",
        "service_type": "hospital",
        "phone": "01-5970032",
        "address": "Thapathali, Kathmandu",
        "latitude": 27.6925,
        "longitude": 85.3187,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    # --- Hospitals: Lalitpur / Bhaktapur ---
    {
        "name_en": "Patan Hospital",
        "name_ne": "पाटन अस्पताल",
        "service_type": "hospital",
        "phone": "01-5522266",
        "address": "Lagankhel, Lalitpur",
        "latitude": 27.6683,
        "longitude": 85.3188,
        "municipality_code": "LMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "B&B Hospital",
        "name_ne": "बी एण्ड बी अस्पताल",
        "service_type": "hospital",
        "phone": "01-5533206",
        "address": "Gwarko, Lalitpur",
        "latitude": 27.6647,
        "longitude": 85.3290,
        "municipality_code": "LMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Bhaktapur Hospital",
        "name_ne": "भक्तपुर अस्पताल",
        "service_type": "hospital",
        "phone": "01-6610676",
        "address": "Doodhpati, Bhaktapur",
        "latitude": 27.6720,
        "longitude": 85.4240,
        "municipality_code": "BKT",
        "is_24x7": True,
        "is_emergency": True,
    },
    # --- Ambulance operators ---
    {
        "name_en": "Nepal Ambulance Service",
        "name_ne": "नेपाल एम्बुलेन्स सेवा",
        "service_type": "ambulance",
        "phone": "102",
        "alt_phone": "01-4427833",
        "address": "Sinamangal, Kathmandu",
        "latitude": 27.6979,
        "longitude": 85.3532,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Nepal Redcross Ambulance",
        "name_ne": "नेपाल रेडक्रस एम्बुलेन्स",
        "service_type": "ambulance",
        "phone": "01-4270650",
        "address": "Kalimati, Kathmandu",
        "latitude": 27.6994,
        "longitude": 85.2961,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    # --- Police ---
    {
        "name_en": "Metropolitan Police Range, Teku",
        "name_ne": "महानगरीय प्रहरी परिसर, टेकु",
        "service_type": "police",
        "phone": "01-4261945",
        "address": "Teku, Kathmandu",
        "latitude": 27.6959,
        "longitude": 85.3062,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "District Police Office, Lalitpur",
        "name_ne": "जिल्ला प्रहरी कार्यालय, ललितपुर",
        "service_type": "police",
        "phone": "01-5521207",
        "address": "Jawalakhel, Lalitpur",
        "latitude": 27.6714,
        "longitude": 85.3126,
        "municipality_code": "LMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "District Police Office, Bhaktapur",
        "name_ne": "जिल्ला प्रहरी कार्यालय, भक्तपुर",
        "service_type": "police",
        "phone": "01-6610127",
        "address": "Bhaktapur",
        "latitude": 27.6722,
        "longitude": 85.4298,
        "municipality_code": "BKT",
        "is_24x7": True,
        "is_emergency": True,
    },
    # --- Fire ---
    {
        "name_en": "Juddha Barun Yantra (Fire Station)",
        "name_ne": "जुद्ध बारुण यन्त्र",
        "service_type": "fire",
        "phone": "101",
        "alt_phone": "01-4221177",
        "address": "Basantapur, Kathmandu",
        "latitude": 27.7041,
        "longitude": 85.3070,
        "municipality_code": "KMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    {
        "name_en": "Lalitpur Fire Station",
        "name_ne": "ललितपुर दमकल केन्द्र",
        "service_type": "fire",
        "phone": "01-5521111",
        "address": "Pulchowk, Lalitpur",
        "latitude": 27.6785,
        "longitude": 85.3159,
        "municipality_code": "LMC",
        "is_24x7": True,
        "is_emergency": True,
    },
    # --- Municipality offices ---
    {
        "name_en": "Kathmandu Metropolitan City Office",
        "name_ne": "काठमाडौं महानगरपालिका कार्यालय",
        "service_type": "municipality_office",
        "phone": "01-4230100",
        "address": "Bagdurbar, Kathmandu",
        "latitude": 27.7010,
        "longitude": 85.3140,
        "municipality_code": "KMC",
        "is_24x7": False,
        "notes_en": "Sunday to Friday, 10:00 to 17:00.",
        "notes_ne": "आइतबारदेखि शुक्रबार, १०:०० देखि १७:००।",
    },
    {
        "name_en": "Lalitpur Metropolitan City Office",
        "name_ne": "ललितपुर महानगरपालिका कार्यालय",
        "service_type": "municipality_office",
        "phone": "01-5521101",
        "address": "Pulchowk, Lalitpur",
        "latitude": 27.6776,
        "longitude": 85.3170,
        "municipality_code": "LMC",
        "is_24x7": False,
    },
    {
        "name_en": "Bhaktapur Municipality Office",
        "name_ne": "भक्तपुर नगरपालिका कार्यालय",
        "service_type": "municipality_office",
        "phone": "01-6610213",
        "address": "Bhaktapur Durbar Square",
        "latitude": 27.6720,
        "longitude": 85.4280,
        "municipality_code": "BKT",
        "is_24x7": False,
    },
    # --- Shelters ---
    {
        "name_en": "Tundikhel Open Space (Emergency Shelter)",
        "name_ne": "टुँडिखेल खुला क्षेत्र (आपतकालीन आश्रय)",
        "service_type": "shelter",
        "address": "Tundikhel, Kathmandu",
        "latitude": 27.7020,
        "longitude": 85.3160,
        "municipality_code": "KMC",
        "is_24x7": True,
        "notes_en": "Designated open space for earthquake evacuation.",
        "notes_ne": "भूकम्प निकासीका लागि तोकिएको खुला क्षेत्र।",
    },
    {
        "name_en": "Jawalakhel Ground (Emergency Shelter)",
        "name_ne": "जावलाखेल मैदान (आपतकालीन आश्रय)",
        "service_type": "shelter",
        "address": "Jawalakhel, Lalitpur",
        "latitude": 27.6702,
        "longitude": 85.3113,
        "municipality_code": "LMC",
        "is_24x7": True,
    },
    {
        "name_en": "Khulla Manch (Emergency Shelter)",
        "name_ne": "खुल्ला मञ्च (आपतकालीन आश्रय)",
        "service_type": "shelter",
        "address": "Ratna Park, Kathmandu",
        "latitude": 27.7048,
        "longitude": 85.3145,
        "municipality_code": "KMC",
        "is_24x7": True,
    },
]
